# Generated by Django 5.2.5 on 2025-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pointofinterest',
            constraint=models.UniqueConstraint(fields=('external_id',), name='unique_external_id'),
        ),
    ]
